### ISSUE TITLE
Interested in service account rotator

### ISSUE THREAD

**Issue by pidah** [ericchiang/kube-service-account-rotator#1]
HI @ericchiang , I just stumbled on this as we are looking at how to rotate service account creds atm. Do you suggest implementing this controller or would you advise something else ? Thanks a lot for your response!

**Comment by ericchiang** [comment]
Hi @pidah,

Discussing general strategies for service account rotation is a bit beyond the scope of this project. I found https://github.com/kubernetes/kubernetes/issues/20165 and will open a docs PR on the main Kubernetes repo to document the options. Please follow discussion there.

**Comment by pidah** [comment]
thanks! @ericchiang
